services:
  - type: web
    name: chit-fund-calculator
    env: static
    buildCommand: echo "Static site - no build required"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html